/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module ksa4_reg(clk, rst_n, a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  input [3:0] a;
  wire [3:0] a;
  wire [3:0] a_q;
  input [3:0] b;
  wire [3:0] b;
  wire [3:0] b_q;
  input cin;
  wire cin;
  wire cin_q;
  input clk;
  wire clk;
  output cout;
  wire cout;
  wire cout_c;
  wire [3:0] g2;
  input rst_n;
  wire rst_n;
  output [3:0] sum;
  wire [3:0] sum;
  wire [3:0] sum_c;
  NAND2_X1 _29_ (
    .A1(a_q[3]),
    .A2(b_q[3]),
    .ZN(_00_)
  );
  AND2_X1 _30_ (
    .A1(a_q[2]),
    .A2(b_q[2]),
    .ZN(_01_)
  );
  NAND2_X1 _31_ (
    .A1(a_q[1]),
    .A2(b_q[1]),
    .ZN(_02_)
  );
  AND2_X1 _32_ (
    .A1(a_q[0]),
    .A2(b_q[0]),
    .ZN(_03_)
  );
  OR2_X1 _33_ (
    .A1(a_q[0]),
    .A2(b_q[0]),
    .ZN(_04_)
  );
  XNOR2_X1 _34_ (
    .A(a_q[0]),
    .B(b_q[0]),
    .ZN(_05_)
  );
  AOI21_X1 _35_ (
    .A(_03_),
    .B1(_04_),
    .B2(cin_q),
    .ZN(_06_)
  );
  NOR2_X1 _36_ (
    .A1(a_q[1]),
    .A2(b_q[1]),
    .ZN(_07_)
  );
  XOR2_X1 _37_ (
    .A(a_q[1]),
    .B(b_q[1]),
    .Z(_08_)
  );
  OAI21_X1 _38_ (
    .A(_02_),
    .B1(_06_),
    .B2(_07_),
    .ZN(_09_)
  );
  OR2_X1 _39_ (
    .A1(a_q[2]),
    .A2(b_q[2]),
    .ZN(_10_)
  );
  XNOR2_X1 _40_ (
    .A(a_q[2]),
    .B(b_q[2]),
    .ZN(_11_)
  );
  AOI21_X1 _41_ (
    .A(_01_),
    .B1(_09_),
    .B2(_10_),
    .ZN(_12_)
  );
  NOR2_X1 _42_ (
    .A1(a_q[3]),
    .A2(b_q[3]),
    .ZN(_13_)
  );
  XOR2_X1 _43_ (
    .A(a_q[3]),
    .B(b_q[3]),
    .Z(_14_)
  );
  OAI21_X1 _44_ (
    .A(_00_),
    .B1(_12_),
    .B2(_13_),
    .ZN(cout_c)
  );
  XNOR2_X1 _45_ (
    .A(cin_q),
    .B(_05_),
    .ZN(sum_c[0])
  );
  XNOR2_X1 _46_ (
    .A(_06_),
    .B(_08_),
    .ZN(sum_c[1])
  );
  XNOR2_X1 _47_ (
    .A(_09_),
    .B(_11_),
    .ZN(sum_c[2])
  );
  XNOR2_X1 _48_ (
    .A(_12_),
    .B(_14_),
    .ZN(sum_c[3])
  );
  DFFR_X1 _49_ (
    .CK(clk),
    .D(sum_c[0]),
    .Q(sum[0]),
    .QN(_16_),
    .RN(rst_n)
  );
  DFFR_X1 _50_ (
    .CK(clk),
    .D(sum_c[1]),
    .Q(sum[1]),
    .QN(_17_),
    .RN(rst_n)
  );
  DFFR_X1 _51_ (
    .CK(clk),
    .D(sum_c[2]),
    .Q(sum[2]),
    .QN(_18_),
    .RN(rst_n)
  );
  DFFR_X1 _52_ (
    .CK(clk),
    .D(sum_c[3]),
    .Q(sum[3]),
    .QN(_19_),
    .RN(rst_n)
  );
  DFFR_X1 _53_ (
    .CK(clk),
    .D(cout_c),
    .Q(cout),
    .QN(_20_),
    .RN(rst_n)
  );
  DFFR_X1 _54_ (
    .CK(clk),
    .D(a[0]),
    .Q(a_q[0]),
    .QN(_21_),
    .RN(rst_n)
  );
  DFFR_X1 _55_ (
    .CK(clk),
    .D(a[1]),
    .Q(a_q[1]),
    .QN(_22_),
    .RN(rst_n)
  );
  DFFR_X1 _56_ (
    .CK(clk),
    .D(a[2]),
    .Q(a_q[2]),
    .QN(_23_),
    .RN(rst_n)
  );
  DFFR_X1 _57_ (
    .CK(clk),
    .D(a[3]),
    .Q(a_q[3]),
    .QN(_24_),
    .RN(rst_n)
  );
  DFFR_X1 _58_ (
    .CK(clk),
    .D(b[0]),
    .Q(b_q[0]),
    .QN(_25_),
    .RN(rst_n)
  );
  DFFR_X1 _59_ (
    .CK(clk),
    .D(b[1]),
    .Q(b_q[1]),
    .QN(_26_),
    .RN(rst_n)
  );
  DFFR_X1 _60_ (
    .CK(clk),
    .D(b[2]),
    .Q(b_q[2]),
    .QN(_27_),
    .RN(rst_n)
  );
  DFFR_X1 _61_ (
    .CK(clk),
    .D(b[3]),
    .Q(b_q[3]),
    .QN(_28_),
    .RN(rst_n)
  );
  DFFR_X1 _62_ (
    .CK(clk),
    .D(cin),
    .Q(cin_q),
    .QN(_15_),
    .RN(rst_n)
  );
  assign g2[3] = cout_c;
endmodule
